#!/usr/bin/perl
use strict;
use warnings;
use utf8;
my $filename = "any.txt";
unless ( open(FILE, $filename) ) {
    print "Cannot open file \"$filename\"\n\n";
    exit;
}
 open Output, '>', 'any.txt' or die "Could not open 'any.txt' $!";
my %count;

open(my $fh, "<", $filename)
    or die "Could not open '$filename': $!"; 
while (my $line = <$fh>) {
    chomp $line;
    my @words = split / /, $line;
    foreach my $word (@words) {
        $count{$word}++;
    }
}



foreach my $word (keys %count) {
    print Output"$word : $count{$word}\n";
}
